-- Fabric Flo — run entire file in Supabase SQL Editor (new project)
-- Generated by npm run supabase:bundle — 9 migrations
-- After this: configure Auth URLs and deploy the web app with VITE_* env vars (see docs/BACKEND_SETUP.md)

-- Defer function-body validation so migrations can define functions before the
-- tables they reference (e.g. is_production_member before production_members).
-- Safe: the function bodies still run correctly once all tables exist.
set check_function_bodies = off;

-- ========== 001_user_app_state.sql ==========

-- Run in Supabase SQL Editor (or via CLI) before using cloud sync in Fabric Flo.
-- Stores one JSON blob per authenticated user. Security relies on RLS + anon key in the browser.

create table if not exists public.user_app_state (
  user_id uuid primary key references auth.users (id) on delete cascade,
  state jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

alter table public.user_app_state enable row level security;

create policy "user_app_state_select_own"
  on public.user_app_state
  for select
  using (auth.uid() = user_id);

create policy "user_app_state_insert_own"
  on public.user_app_state
  for insert
  with check (auth.uid() = user_id);

create policy "user_app_state_update_own"
  on public.user_app_state
  for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

-- Optional: allow delete (app does not require it)
create policy "user_app_state_delete_own"
  on public.user_app_state
  for delete
  using (auth.uid() = user_id);

-- ========== 002_productions_normalized_rls.sql ==========

-- Fabric Flo: normalized multi-tenant schema + membership (RBAC)
-- Apply after 001_user_app_state.sql (legacy blob can coexist until clients migrate).

-- ---------------------------------------------------------------------------
-- Helper: membership check (SECURITY INVOKER — uses caller RLS on members)
-- ---------------------------------------------------------------------------
create or replace function public.is_production_member(p_production_id uuid, p_roles text[] default null)
returns boolean
language sql
stable
security invoker
set search_path = public
as $$
  select exists (
    select 1
    from public.production_members m
    where m.production_id = p_production_id
      and m.user_id = auth.uid()
      and (p_roles is null or m.role = any (p_roles))
  );
$$;

-- ---------------------------------------------------------------------------
-- Productions
-- ---------------------------------------------------------------------------
create table if not exists public.productions (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text unique,
  version bigint not null default 1,
  settings jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  archived_at timestamptz
);

create index if not exists productions_archived_at_idx on public.productions (archived_at) where archived_at is null;

-- ---------------------------------------------------------------------------
-- Members (replaces plaintext PIN as primary gate; PIN may live in settings during transition)
-- Roles: admin, department_head, crew, viewer
-- ---------------------------------------------------------------------------
create table if not exists public.production_members (
  production_id uuid not null references public.productions (id) on delete cascade,
  user_id uuid not null references auth.users (id) on delete cascade,
  role text not null check (role in ('admin', 'department_head', 'crew', 'viewer')),
  created_at timestamptz not null default now(),
  primary key (production_id, user_id)
);

create index if not exists production_members_user_id_idx on public.production_members (user_id);

-- ---------------------------------------------------------------------------
-- Invites (token_hash = hex digest of random token; never store raw token)
-- ---------------------------------------------------------------------------
create table if not exists public.production_invites (
  id uuid primary key default gen_random_uuid(),
  production_id uuid not null references public.productions (id) on delete cascade,
  email text,
  role text not null check (role in ('admin', 'department_head', 'crew', 'viewer')),
  token_hash text not null unique,
  expires_at timestamptz not null,
  created_by uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists production_invites_production_id_idx on public.production_invites (production_id);

-- ---------------------------------------------------------------------------
-- Locations
-- ---------------------------------------------------------------------------
create table if not exists public.locations (
  id uuid primary key default gen_random_uuid(),
  production_id uuid not null references public.productions (id) on delete cascade,
  kind text not null check (kind in ('studio', 'filming_location', 'transport_truck')),
  name text not null,
  sort_order int not null default 0,
  created_at timestamptz not null default now()
);

create index if not exists locations_production_id_idx on public.locations (production_id);

-- ---------------------------------------------------------------------------
-- Inventory items
-- ---------------------------------------------------------------------------
create table if not exists public.inventory_items (
  id uuid primary key default gen_random_uuid(),
  production_id uuid not null references public.productions (id) on delete cascade,
  kind text not null check (kind in ('fabric', 'bag')),
  name text not null,
  size text,
  notes text,
  condition text check (condition is null or condition in ('ok', 'lost', 'damaged')),
  stable_public_id text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  row_version bigint not null default 1
);

create index if not exists inventory_items_production_id_idx on public.inventory_items (production_id);
create unique index if not exists inventory_items_stable_public_id_uidx
  on public.inventory_items (production_id, stable_public_id)
  where stable_public_id is not null;

-- ---------------------------------------------------------------------------
-- QR aliases (rotating / dynamic codes)
-- ---------------------------------------------------------------------------
create table if not exists public.item_qr_aliases (
  id uuid primary key default gen_random_uuid(),
  item_id uuid not null references public.inventory_items (id) on delete cascade,
  alias text not null,
  created_at timestamptz not null default now(),
  unique (item_id, alias)
);

create index if not exists item_qr_aliases_alias_idx on public.item_qr_aliases (alias);

-- ---------------------------------------------------------------------------
-- Scan events (append-only; idempotency for flaky mobile networks)
-- ---------------------------------------------------------------------------
create table if not exists public.scan_events (
  id uuid primary key default gen_random_uuid(),
  production_id uuid not null references public.productions (id) on delete cascade,
  item_id uuid not null references public.inventory_items (id) on delete cascade,
  location_id uuid references public.locations (id) on delete set null,
  item_kind text not null check (item_kind in ('fabric', 'bag')),
  item_name text not null,
  location_kind text not null check (location_kind in ('studio', 'filming_location', 'transport_truck')),
  location_label text not null,
  scanned_at timestamptz not null,
  raw_qr text not null,
  scanned_by uuid references auth.users (id) on delete set null,
  idempotency_key text unique,
  created_at timestamptz not null default now()
);

create index if not exists scan_events_production_scanned_at_idx
  on public.scan_events (production_id, scanned_at desc);
create index if not exists scan_events_item_id_idx on public.scan_events (item_id);

-- ---------------------------------------------------------------------------
-- RLS
-- ---------------------------------------------------------------------------
alter table public.productions enable row level security;
alter table public.production_members enable row level security;
alter table public.production_invites enable row level security;
alter table public.locations enable row level security;
alter table public.inventory_items enable row level security;
alter table public.item_qr_aliases enable row level security;
alter table public.scan_events enable row level security;

-- Members: each user reads their own membership rows
create policy production_members_select_own
  on public.production_members for select
  using (user_id = auth.uid());

-- Productions: visible if member
create policy productions_select_member
  on public.productions for select
  using (public.is_production_member(id));

-- Inserts: only via RPC in practice; allow admin insert for bootstrap if needed — deny direct insert
create policy productions_no_direct_insert
  on public.productions for insert
  with check (false);

create policy productions_update_admin
  on public.productions for update
  using (public.is_production_member(id, array['admin', 'department_head']::text[]))
  with check (public.is_production_member(id, array['admin', 'department_head']::text[]));

-- production_members: managed by RPC / service; deny direct writes from clients
create policy production_members_no_direct_write
  on public.production_members for all
  using (false);

-- invites: members with admin or department_head can read invites for their production
create policy production_invites_select_heads
  on public.production_invites for select
  using (public.is_production_member(production_id, array['admin', 'department_head']::text[]));

create policy production_invites_no_direct_mutate
  on public.production_invites for insert
  with check (false);

-- locations
create policy locations_select_member
  on public.locations for select
  using (public.is_production_member(production_id));

create policy locations_mutate_heads
  on public.locations for all
  using (public.is_production_member(production_id, array['admin', 'department_head']::text[]))
  with check (public.is_production_member(production_id, array['admin', 'department_head']::text[]));

-- inventory_items
create policy inventory_items_select_member
  on public.inventory_items for select
  using (public.is_production_member(production_id));

create policy inventory_items_mutate_heads
  on public.inventory_items for all
  using (public.is_production_member(production_id, array['admin', 'department_head']::text[]))
  with check (public.is_production_member(production_id, array['admin', 'department_head']::text[]));

-- item_qr_aliases (join item -> production)
create policy item_qr_aliases_select_member
  on public.item_qr_aliases for select
  using (
    exists (
      select 1 from public.inventory_items i
      where i.id = item_qr_aliases.item_id
        and public.is_production_member(i.production_id)
    )
  );

create policy item_qr_aliases_mutate_heads
  on public.item_qr_aliases for all
  using (
    exists (
      select 1 from public.inventory_items i
      where i.id = item_qr_aliases.item_id
        and public.is_production_member(i.production_id, array['admin', 'department_head']::text[])
    )
  )
  with check (
    exists (
      select 1 from public.inventory_items i
      where i.id = item_qr_aliases.item_id
        and public.is_production_member(i.production_id, array['admin', 'department_head']::text[])
    )
  );

-- scan_events: members can read; crew+ can insert (handled by RPC); restrict direct insert
create policy scan_events_select_member
  on public.scan_events for select
  using (public.is_production_member(production_id));

create policy scan_events_insert_member
  on public.scan_events for insert
  with check (
    public.is_production_member(production_id, array['admin', 'department_head', 'crew']::text[])
  );

create policy scan_events_no_update
  on public.scan_events for update
  using (false);

create policy scan_events_no_delete
  on public.scan_events for delete
  using (false);

-- ========== 003_fabric_flo_rpcs.sql ==========

-- Fabric Flo: SECURITY DEFINER RPCs for bundle pull/push + bootstrap create production.
-- Requires migration 002.

-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_create_production(p_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;
  if trim(p_name) = '' then
    raise exception 'invalid_name';
  end if;

  insert into public.productions (name)
  values (trim(p_name))
  returning id into v_id;

  insert into public.production_members (production_id, user_id, role)
  values (v_id, auth.uid(), 'admin');

  return v_id;
end;
$$;

grant execute on function public.fabric_flo_create_production(text) to authenticated;

-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_pull()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_productions jsonb := '[]'::jsonb;
  v_scans jsonb := '[]'::jsonb;
  v_versions jsonb := '{}'::jsonb;
  r_prod record;
  v_loc jsonb;
  v_items jsonb;
  v_item record;
  v_scan record;
  v_pin text;
  v_qr text[];
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  for r_prod in
    select p.*
    from public.productions p
    join public.production_members m on m.production_id = p.id
    where m.user_id = v_uid
      and p.archived_at is null
    order by p.created_at asc
  loop
    v_versions := v_versions || jsonb_build_object(r_prod.id::text, r_prod.version);

    v_pin := nullif(r_prod.settings ->> 'departmentHeadPin', '');

    select coalesce(jsonb_agg(
      jsonb_build_object(
        'id', l.id,
        'kind', l.kind,
        'name', l.name
      ) order by l.sort_order, l.name
    ), '[]'::jsonb)
    into v_loc
    from public.locations l
    where l.production_id = r_prod.id;

    v_items := '[]'::jsonb;
    for v_item in
      select i.*
      from public.inventory_items i
      where i.production_id = r_prod.id
      order by i.name
    loop
      select coalesce(array_agg(a.alias order by a.created_at), array[]::text[])
      into v_qr
      from public.item_qr_aliases a
      where a.item_id = v_item.id;

      v_items := v_items || jsonb_build_array(
        jsonb_build_object(
          'id', v_item.id,
          'kind', v_item.kind,
          'name', v_item.name,
          'qrAliases', to_jsonb(v_qr),
          'size', v_item.size,
          'notes', v_item.notes,
          'condition', v_item.condition
        )
      );
    end loop;

    v_productions := v_productions || jsonb_build_array(
      jsonb_build_object(
        'id', r_prod.id,
        'name', r_prod.name,
        'createdAt', to_jsonb(r_prod.created_at),
        'departmentHeadPin', to_jsonb(v_pin),
        'locations', coalesce(v_loc, '[]'::jsonb),
        'items', coalesce(v_items, '[]'::jsonb)
      )
    );
  end loop;

  for v_scan in
    select s.*
    from public.scan_events s
    where public.is_production_member(s.production_id)
    order by s.scanned_at desc
  loop
    v_scans := v_scans || jsonb_build_array(
      jsonb_build_object(
        'id', v_scan.id,
        'productionId', v_scan.production_id,
        'itemId', v_scan.item_id,
        'itemKind', v_scan.item_kind,
        'itemName', v_scan.item_name,
        'locationId', coalesce(v_scan.location_id::text, ''),
        'locationKind', v_scan.location_kind,
        'locationLabel', v_scan.location_label,
        'scannedAt', to_jsonb(v_scan.scanned_at),
        'rawQr', v_scan.raw_qr
      )
    );
  end loop;

  return jsonb_build_object(
    'productions', v_productions,
    'scanLog', v_scans,
    'activeProductionId', null::jsonb,
    'versions', v_versions
  );
end;
$$;

grant execute on function public.fabric_flo_pull() to authenticated;

-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_push(p_state jsonb, p_expected_versions jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_prod record;
  v_pid uuid;
  v_exp bigint;
  v_cur bigint;
  v_loc jsonb;
  v_item jsonb;
  v_scan jsonb;
  v_sid uuid;
  v_settings jsonb;
  v_versions jsonb := '{}'::jsonb;
  v_ik text;
  v_update_count int;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  if p_state is null or jsonb_typeof(p_state -> 'productions') <> 'array' then
    raise exception 'invalid_state';
  end if;

  for v_prod in select * from jsonb_array_elements(coalesce(p_state -> 'productions', '[]'::jsonb))
  loop
    v_pid := (v_prod.value ->> 'id')::uuid;
    if v_pid is null then
      continue;
    end if;

    if not exists (select 1 from public.productions where id = v_pid) then
      raise exception 'unknown_production %', v_pid;
    end if;

    if not public.is_production_member(
      v_pid,
      array['admin', 'department_head', 'crew']::text[]
    ) then
      raise exception 'forbidden_production %', v_pid;
    end if;

    if p_expected_versions ? v_pid::text then
      v_exp := (p_expected_versions ->> v_pid::text)::bigint;
      select version into v_cur from public.productions where id = v_pid for update;
      if v_cur is distinct from v_exp then
        raise exception 'version_conflict'
          using errcode = 'P0001',
            message = format('production=%s server_version=%s', v_pid, v_cur);
      end if;
    end if;

    delete from public.scan_events where production_id = v_pid;
    delete from public.item_qr_aliases a
      using public.inventory_items i
      where a.item_id = i.id and i.production_id = v_pid;
    delete from public.inventory_items where production_id = v_pid;
    delete from public.locations where production_id = v_pid;

    v_settings := coalesce(v_prod.value -> 'settings', '{}'::jsonb);
    if (v_prod.value ? 'departmentHeadPin') then
      v_settings := v_settings || jsonb_build_object(
        'departmentHeadPin',
        nullif(v_prod.value ->> 'departmentHeadPin', '')
      );
    end if;

    update public.productions
    set
      name = coalesce(nullif(trim(v_prod.value ->> 'name'), ''), name),
      settings = coalesce(v_settings, '{}'::jsonb),
      updated_at = now(),
      version = version + 1
    where id = v_pid
    returning version into v_cur;

    get diagnostics v_update_count = row_count;
    if v_update_count = 0 then
      raise exception 'unknown_production %', v_pid;
    end if;

    v_versions := v_versions || jsonb_build_object(v_pid::text, v_cur);

    for v_loc in select * from jsonb_array_elements(coalesce(v_prod.value -> 'locations', '[]'::jsonb))
    loop
      insert into public.locations (id, production_id, kind, name, sort_order)
      values (
        coalesce((v_loc.value ->> 'id')::uuid, gen_random_uuid()),
        v_pid,
        v_loc.value ->> 'kind',
        v_loc.value ->> 'name',
        coalesce((v_loc.value ->> 'sort_order')::int, 0)
      );
    end loop;

    for v_item in select * from jsonb_array_elements(coalesce(v_prod.value -> 'items', '[]'::jsonb))
    loop
      v_sid := coalesce((v_item.value ->> 'id')::uuid, gen_random_uuid());
      insert into public.inventory_items (
        id, production_id, kind, name, size, notes, condition, stable_public_id
      )
      values (
        v_sid,
        v_pid,
        v_item.value ->> 'kind',
        v_item.value ->> 'name',
        nullif(trim(v_item.value ->> 'size'), ''),
        nullif(v_item.value ->> 'notes', ''),
        nullif(v_item.value ->> 'condition', ''),
        v_item.value ->> 'id'
      );

      if jsonb_typeof(v_item.value -> 'qrAliases') = 'array' then
        insert into public.item_qr_aliases (item_id, alias)
        select v_sid, trim(x)
        from jsonb_array_elements_text(v_item.value -> 'qrAliases') as t(x)
        where trim(x) <> ''
        on conflict (item_id, alias) do nothing;
      end if;
    end loop;
  end loop;

  for v_scan in select * from jsonb_array_elements(coalesce(p_state -> 'scanLog', '[]'::jsonb))
  loop
    v_pid := (v_scan.value ->> 'productionId')::uuid;
    if not exists (
      select 1
      from jsonb_array_elements(coalesce(p_state -> 'productions', '[]'::jsonb)) pe
      where (pe.value ->> 'id')::uuid = v_pid
    ) then
      continue;
    end if;

    if not public.is_production_member(
      v_pid,
      array['admin', 'department_head', 'crew']::text[]
    ) then
      continue;
    end if;

    v_ik := nullif(trim(v_scan.value ->> 'idempotencyKey'), '');

    if v_ik is not null then
      insert into public.scan_events (
        id, production_id, item_id, location_id,
        item_kind, item_name, location_kind, location_label,
        scanned_at, raw_qr, scanned_by, idempotency_key
      )
      values (
        coalesce((v_scan.value ->> 'id')::uuid, gen_random_uuid()),
        v_pid,
        (v_scan.value ->> 'itemId')::uuid,
        nullif(v_scan.value ->> 'locationId', '')::uuid,
        v_scan.value ->> 'itemKind',
        v_scan.value ->> 'itemName',
        v_scan.value ->> 'locationKind',
        v_scan.value ->> 'locationLabel',
        coalesce((v_scan.value ->> 'scannedAt')::timestamptz, now()),
        v_scan.value ->> 'rawQr',
        v_uid,
        v_ik
      )
      on conflict (idempotency_key) do nothing;
    else
      insert into public.scan_events (
        id, production_id, item_id, location_id,
        item_kind, item_name, location_kind, location_label,
        scanned_at, raw_qr, scanned_by, idempotency_key
      )
      values (
        coalesce((v_scan.value ->> 'id')::uuid, gen_random_uuid()),
        v_pid,
        (v_scan.value ->> 'itemId')::uuid,
        nullif(v_scan.value ->> 'locationId', '')::uuid,
        v_scan.value ->> 'itemKind',
        v_scan.value ->> 'itemName',
        v_scan.value ->> 'locationKind',
        v_scan.value ->> 'locationLabel',
        coalesce((v_scan.value ->> 'scannedAt')::timestamptz, now()),
        v_scan.value ->> 'rawQr',
        v_uid,
        null
      );
    end if;
  end loop;

  return jsonb_build_object('ok', true, 'versions', v_versions);
end;
$$;

grant execute on function public.fabric_flo_push(jsonb, jsonb) to authenticated;

-- ========== 004_fabric_flo_audit_log.sql ==========

-- Append-only audit trail for security-relevant actions (RLS: admins/heads read only).

create table if not exists public.fabric_flo_audit_log (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users (id) on delete set null,
  production_id uuid references public.productions (id) on delete set null,
  action text not null,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists fabric_flo_audit_log_production_id_idx
  on public.fabric_flo_audit_log (production_id, created_at desc);

alter table public.fabric_flo_audit_log enable row level security;

create policy fabric_flo_audit_log_select_heads
  on public.fabric_flo_audit_log for select
  using (
    production_id is not null
    and public.is_production_member(
      production_id,
      array['admin', 'department_head']::text[]
    )
  );

create policy fabric_flo_audit_log_no_client_write
  on public.fabric_flo_audit_log for insert
  with check (false);

create policy fabric_flo_audit_log_no_update
  on public.fabric_flo_audit_log for update
  using (false);

create policy fabric_flo_audit_log_no_delete
  on public.fabric_flo_audit_log for delete
  using (false);

-- Inserts are intended from SECURITY DEFINER RPCs or service role (bypasses RLS).

-- ========== 005_fabric_flo_phase2.sql ==========

-- Phase 2: audit logging, production invites, server-side inventory import.
-- Requires 002–004.

create extension if not exists pgcrypto;

-- ---------------------------------------------------------------------------
-- Audit helper (SECURITY DEFINER — bypasses RLS insert deny on audit table)
-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_audit(
  p_production_id uuid,
  p_action text,
  p_detail jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.fabric_flo_audit_log (user_id, production_id, action, detail)
  values (auth.uid(), p_production_id, p_action, coalesce(p_detail, '{}'::jsonb));
end;
$$;

-- ---------------------------------------------------------------------------
-- Create production (+ audit)
-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_create_production(p_name text)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_id uuid;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;
  if trim(p_name) = '' then
    raise exception 'invalid_name';
  end if;

  insert into public.productions (name)
  values (trim(p_name))
  returning id into v_id;

  insert into public.production_members (production_id, user_id, role)
  values (v_id, auth.uid(), 'admin');

  perform public.fabric_flo_audit(v_id, 'production_created', jsonb_build_object('name', trim(p_name)));

  return v_id;
end;
$$;

-- ---------------------------------------------------------------------------
-- Push (+ per-production audit)
-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_push(p_state jsonb, p_expected_versions jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_prod record;
  v_pid uuid;
  v_exp bigint;
  v_cur bigint;
  v_loc jsonb;
  v_item jsonb;
  v_scan jsonb;
  v_sid uuid;
  v_settings jsonb;
  v_versions jsonb := '{}'::jsonb;
  v_ik text;
  v_update_count int;
  v_item_count int;
  v_loc_count int;
  v_scan_count int;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  if p_state is null or jsonb_typeof(p_state -> 'productions') <> 'array' then
    raise exception 'invalid_state';
  end if;

  for v_prod in select * from jsonb_array_elements(coalesce(p_state -> 'productions', '[]'::jsonb))
  loop
    v_pid := (v_prod.value ->> 'id')::uuid;
    if v_pid is null then
      continue;
    end if;

    if not exists (select 1 from public.productions where id = v_pid) then
      raise exception 'unknown_production %', v_pid;
    end if;

    if not public.is_production_member(
      v_pid,
      array['admin', 'department_head', 'crew']::text[]
    ) then
      raise exception 'forbidden_production %', v_pid;
    end if;

    if p_expected_versions ? v_pid::text then
      v_exp := (p_expected_versions ->> v_pid::text)::bigint;
      select version into v_cur from public.productions where id = v_pid for update;
      if v_cur is distinct from v_exp then
        raise exception 'version_conflict'
          using errcode = 'P0001',
            message = format('production=%s server_version=%s', v_pid, v_cur);
      end if;
    end if;

    delete from public.scan_events where production_id = v_pid;
    delete from public.item_qr_aliases a
      using public.inventory_items i
      where a.item_id = i.id and i.production_id = v_pid;
    delete from public.inventory_items where production_id = v_pid;
    delete from public.locations where production_id = v_pid;

    v_settings := coalesce(v_prod.value -> 'settings', '{}'::jsonb);
    if (v_prod.value ? 'departmentHeadPin') then
      v_settings := v_settings || jsonb_build_object(
        'departmentHeadPin',
        nullif(v_prod.value ->> 'departmentHeadPin', '')
      );
    end if;

    update public.productions
    set
      name = coalesce(nullif(trim(v_prod.value ->> 'name'), ''), name),
      settings = coalesce(v_settings, '{}'::jsonb),
      updated_at = now(),
      version = version + 1
    where id = v_pid
    returning version into v_cur;

    get diagnostics v_update_count = row_count;
    if v_update_count = 0 then
      raise exception 'unknown_production %', v_pid;
    end if;

    v_versions := v_versions || jsonb_build_object(v_pid::text, v_cur);

    v_loc_count := 0;
    for v_loc in select * from jsonb_array_elements(coalesce(v_prod.value -> 'locations', '[]'::jsonb))
    loop
      v_loc_count := v_loc_count + 1;
      insert into public.locations (id, production_id, kind, name, sort_order)
      values (
        coalesce((v_loc.value ->> 'id')::uuid, gen_random_uuid()),
        v_pid,
        v_loc.value ->> 'kind',
        v_loc.value ->> 'name',
        coalesce((v_loc.value ->> 'sort_order')::int, 0)
      );
    end loop;

    v_item_count := 0;
    for v_item in select * from jsonb_array_elements(coalesce(v_prod.value -> 'items', '[]'::jsonb))
    loop
      v_item_count := v_item_count + 1;
      v_sid := coalesce((v_item.value ->> 'id')::uuid, gen_random_uuid());
      insert into public.inventory_items (
        id, production_id, kind, name, size, notes, condition, stable_public_id
      )
      values (
        v_sid,
        v_pid,
        v_item.value ->> 'kind',
        v_item.value ->> 'name',
        nullif(trim(v_item.value ->> 'size'), ''),
        nullif(v_item.value ->> 'notes', ''),
        nullif(v_item.value ->> 'condition', ''),
        v_item.value ->> 'id'
      );

      if jsonb_typeof(v_item.value -> 'qrAliases') = 'array' then
        insert into public.item_qr_aliases (item_id, alias)
        select v_sid, trim(x)
        from jsonb_array_elements_text(v_item.value -> 'qrAliases') as t(x)
        where trim(x) <> ''
        on conflict (item_id, alias) do nothing;
      end if;
    end loop;

    select count(*)::int into v_scan_count
    from jsonb_array_elements(coalesce(p_state -> 'scanLog', '[]'::jsonb)) se
    where (se.value ->> 'productionId')::uuid = v_pid;

    perform public.fabric_flo_audit(
      v_pid,
      'bundle_push',
      jsonb_build_object(
        'version', v_cur,
        'locations', v_loc_count,
        'items', v_item_count,
        'scans', v_scan_count
      )
    );
  end loop;

  for v_scan in select * from jsonb_array_elements(coalesce(p_state -> 'scanLog', '[]'::jsonb))
  loop
    v_pid := (v_scan.value ->> 'productionId')::uuid;
    if not exists (
      select 1
      from jsonb_array_elements(coalesce(p_state -> 'productions', '[]'::jsonb)) pe
      where (pe.value ->> 'id')::uuid = v_pid
    ) then
      continue;
    end if;

    if not public.is_production_member(
      v_pid,
      array['admin', 'department_head', 'crew']::text[]
    ) then
      continue;
    end if;

    v_ik := nullif(trim(v_scan.value ->> 'idempotencyKey'), '');

    if v_ik is not null then
      insert into public.scan_events (
        id, production_id, item_id, location_id,
        item_kind, item_name, location_kind, location_label,
        scanned_at, raw_qr, scanned_by, idempotency_key
      )
      values (
        coalesce((v_scan.value ->> 'id')::uuid, gen_random_uuid()),
        v_pid,
        (v_scan.value ->> 'itemId')::uuid,
        nullif(v_scan.value ->> 'locationId', '')::uuid,
        v_scan.value ->> 'itemKind',
        v_scan.value ->> 'itemName',
        v_scan.value ->> 'locationKind',
        v_scan.value ->> 'locationLabel',
        coalesce((v_scan.value ->> 'scannedAt')::timestamptz, now()),
        v_scan.value ->> 'rawQr',
        v_uid,
        v_ik
      )
      on conflict (idempotency_key) do nothing;
    else
      insert into public.scan_events (
        id, production_id, item_id, location_id,
        item_kind, item_name, location_kind, location_label,
        scanned_at, raw_qr, scanned_by, idempotency_key
      )
      values (
        coalesce((v_scan.value ->> 'id')::uuid, gen_random_uuid()),
        v_pid,
        (v_scan.value ->> 'itemId')::uuid,
        nullif(v_scan.value ->> 'locationId', '')::uuid,
        v_scan.value ->> 'itemKind',
        v_scan.value ->> 'itemName',
        v_scan.value ->> 'locationKind',
        v_scan.value ->> 'locationLabel',
        coalesce((v_scan.value ->> 'scannedAt')::timestamptz, now()),
        v_scan.value ->> 'rawQr',
        v_uid,
        null
      );
    end if;
  end loop;

  return jsonb_build_object('ok', true, 'versions', v_versions);
end;
$$;

-- ---------------------------------------------------------------------------
-- Create invite (admin / department_head) — returns one-time token
-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_create_invite(
  p_production_id uuid,
  p_role text default 'crew',
  p_email text default null,
  p_expires_days int default 7
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_token text;
  v_hash text;
  v_invite_id uuid;
  v_expires timestamptz;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if not public.is_production_member(
    p_production_id,
    array['admin', 'department_head']::text[]
  ) then
    raise exception 'forbidden';
  end if;

  if p_role not in ('viewer', 'crew', 'department_head') then
    raise exception 'invalid_role';
  end if;

  v_token := encode(gen_random_bytes(24), 'hex');
  v_hash := encode(digest(v_token, 'sha256'), 'hex');
  v_expires := now() + make_interval(days => greatest(1, least(coalesce(p_expires_days, 7), 30)));

  insert into public.production_invites (
    production_id, email, role, token_hash, expires_at, created_by
  )
  values (
    p_production_id,
    nullif(trim(p_email), ''),
    p_role,
    v_hash,
    v_expires,
    auth.uid()
  )
  returning id into v_invite_id;

  perform public.fabric_flo_audit(
    p_production_id,
    'invite_created',
    jsonb_build_object('invite_id', v_invite_id, 'role', p_role, 'email', nullif(trim(p_email), ''))
  );

  return jsonb_build_object(
    'inviteId', v_invite_id,
    'token', v_token,
    'expiresAt', v_expires,
    'role', p_role
  );
end;
$$;

grant execute on function public.fabric_flo_create_invite(uuid, text, text, int) to authenticated;

-- ---------------------------------------------------------------------------
-- Accept invite by token
-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_accept_invite(p_token text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_hash text;
  v_inv record;
  v_email text;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if nullif(trim(p_token), '') is null then
    raise exception 'invalid_token';
  end if;

  v_hash := encode(digest(trim(p_token), 'sha256'), 'hex');

  select i.* into v_inv
  from public.production_invites i
  where i.token_hash = v_hash
    and i.expires_at > now()
  limit 1;

  if not found then
    raise exception 'invite_not_found_or_expired';
  end if;

  if v_inv.email is not null then
    select u.email into v_email from auth.users u where u.id = auth.uid();
    if lower(trim(v_inv.email)) is distinct from lower(trim(coalesce(v_email, ''))) then
      raise exception 'invite_email_mismatch';
    end if;
  end if;

  insert into public.production_members (production_id, user_id, role)
  values (v_inv.production_id, auth.uid(), v_inv.role)
  on conflict (production_id, user_id) do update set role = excluded.role;

  delete from public.production_invites where id = v_inv.id;

  perform public.fabric_flo_audit(
    v_inv.production_id,
    'invite_accepted',
    jsonb_build_object('role', v_inv.role)
  );

  return jsonb_build_object('productionId', v_inv.production_id, 'role', v_inv.role);
end;
$$;

grant execute on function public.fabric_flo_accept_invite(text) to authenticated;

-- ---------------------------------------------------------------------------
-- Server-side inventory merge (parsed rows as jsonb array)
-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_import_inventory_rows(
  p_production_id uuid,
  p_rows jsonb,
  p_expected_version bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
  v_kind text;
  v_name text;
    v_notes text;
    v_size text;
    v_condition text;
  v_item_id uuid;
  v_merged int := 0;
  v_added int := 0;
  v_cur bigint;
  v_row_count int;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if jsonb_typeof(p_rows) <> 'array' then
    raise exception 'invalid_rows';
  end if;

  select jsonb_array_length(p_rows) into v_row_count;
  if v_row_count > 500 then
    raise exception 'too_many_rows';
  end if;

  if not public.is_production_member(
    p_production_id,
    array['admin', 'department_head']::text[]
  ) then
    raise exception 'forbidden';
  end if;

  if p_expected_version is not null then
    select version into v_cur from public.productions where id = p_production_id for update;
    if v_cur is distinct from p_expected_version then
      raise exception 'version_conflict'
        using errcode = 'P0001',
          message = format('production=%s server_version=%s', p_production_id, v_cur);
    end if;
  else
    perform 1 from public.productions where id = p_production_id for update;
  end if;

  for v_row in select * from jsonb_array_elements(p_rows)
  loop
    v_kind := lower(trim(v_row ->> 'kind'));
    v_name := trim(v_row ->> 'name');
    if v_kind not in ('fabric', 'bag') or v_name = '' then
      continue;
    end if;

    v_notes := nullif(trim(v_row ->> 'notes'), '');
    v_size := nullif(trim(v_row ->> 'size'), '');
    v_condition := nullif(trim(v_row ->> 'condition'), '');
    if v_condition not in ('ok', 'lost', 'damaged') then
      v_condition := null;
    end if;

    select i.id into v_item_id
    from public.inventory_items i
    where i.production_id = p_production_id
      and i.kind = v_kind
      and lower(trim(i.name)) = lower(v_name)
    limit 1;

    if found then
      v_merged := v_merged + 1;
      update public.inventory_items i
      set
        size = coalesce(v_size, i.size),
        notes = coalesce(v_notes, i.notes),
        condition = case
          when v_condition in ('lost', 'damaged') then v_condition
          when v_condition = 'ok' then 'ok'
          else i.condition
        end,
        updated_at = now()
      where i.id = v_item_id;

      if jsonb_typeof(v_row -> 'qrAliases') = 'array' then
        insert into public.item_qr_aliases (item_id, alias)
        select v_item_id, trim(x)
        from jsonb_array_elements_text(v_row -> 'qrAliases') as t(x)
        where trim(x) <> ''
        on conflict (item_id, alias) do nothing;
      end if;
    else
      v_added := v_added + 1;
      v_item_id := gen_random_uuid();
      insert into public.inventory_items (
        id, production_id, kind, name, size, notes, condition, stable_public_id
      )
      values (
        v_item_id,
        p_production_id,
        v_kind,
        v_name,
        v_size,
        v_notes,
        v_condition,
        v_item_id::text
      );

      if jsonb_typeof(v_row -> 'qrAliases') = 'array' then
        insert into public.item_qr_aliases (item_id, alias)
        select v_item_id, trim(x)
        from jsonb_array_elements_text(v_row -> 'qrAliases') as t(x)
        where trim(x) <> ''
        on conflict (item_id, alias) do nothing;
      end if;
    end if;
  end loop;

  update public.productions
  set version = version + 1, updated_at = now()
  where id = p_production_id
  returning version into v_cur;

  perform public.fabric_flo_audit(
    p_production_id,
    'inventory_import',
    jsonb_build_object('merged', v_merged, 'added', v_added, 'row_count', v_row_count)
  );

  return jsonb_build_object(
    'merged', v_merged,
    'added', v_added,
    'version', v_cur
  );
end;
$$;

grant execute on function public.fabric_flo_import_inventory_rows(uuid, jsonb, bigint) to authenticated;

-- ========== 006_inventory_item_size.sql ==========

-- Add size column for existing deployments (included in 002 for fresh installs).

alter table public.inventory_items add column if not exists size text;

-- ========== 007_inventory_one_piece_per_row.sql ==========

-- Each CSV/import row is one physical piece (same name + size allowed many times).
-- Rows with a matching Item ID update that piece; otherwise a new row is inserted.

create or replace function public.fabric_flo_import_inventory_rows(
  p_production_id uuid,
  p_rows jsonb,
  p_expected_version bigint default null
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_row jsonb;
  v_kind text;
  v_name text;
  v_notes text;
  v_size text;
  v_condition text;
  v_row_id uuid;
  v_item_id uuid;
  v_merged int := 0;
  v_added int := 0;
  v_cur bigint;
  v_row_count int;
begin
  if auth.uid() is null then
    raise exception 'not_authenticated';
  end if;

  if jsonb_typeof(p_rows) <> 'array' then
    raise exception 'invalid_rows';
  end if;

  select jsonb_array_length(p_rows) into v_row_count;
  if v_row_count > 500 then
    raise exception 'too_many_rows';
  end if;

  if not public.is_production_member(
    p_production_id,
    array['admin', 'department_head']::text[]
  ) then
    raise exception 'forbidden';
  end if;

  if p_expected_version is not null then
    select version into v_cur from public.productions where id = p_production_id for update;
    if v_cur is distinct from p_expected_version then
      raise exception 'version_conflict'
        using errcode = 'P0001',
          message = format('production=%s server_version=%s', p_production_id, v_cur);
    end if;
  else
    perform 1 from public.productions where id = p_production_id for update;
  end if;

  for v_row in select * from jsonb_array_elements(p_rows)
  loop
    v_kind := lower(trim(v_row ->> 'kind'));
    v_name := trim(v_row ->> 'name');
    if v_kind not in ('fabric', 'bag') or v_name = '' then
      continue;
    end if;

    v_notes := nullif(trim(v_row ->> 'notes'), '');
    v_size := nullif(trim(v_row ->> 'size'), '');
    v_condition := nullif(trim(v_row ->> 'condition'), '');
    if v_condition not in ('ok', 'lost', 'damaged') then
      v_condition := null;
    end if;

    v_row_id := null;
    begin
      if nullif(trim(v_row ->> 'id'), '') is not null then
        v_row_id := (trim(v_row ->> 'id'))::uuid;
      end if;
    exception
      when invalid_text_representation then
        v_row_id := null;
    end;

    if v_row_id is not null then
      select i.id into v_item_id
      from public.inventory_items i
      where i.production_id = p_production_id
        and i.id = v_row_id
      limit 1;
    else
      v_item_id := null;
    end if;

    if v_item_id is not null then
      v_merged := v_merged + 1;
      update public.inventory_items i
      set
        kind = v_kind,
        name = v_name,
        size = coalesce(v_size, i.size),
        notes = coalesce(v_notes, i.notes),
        condition = case
          when v_condition in ('lost', 'damaged') then v_condition
          when v_condition = 'ok' then 'ok'
          else i.condition
        end,
        updated_at = now()
      where i.id = v_item_id;

      if jsonb_typeof(v_row -> 'qrAliases') = 'array' then
        insert into public.item_qr_aliases (item_id, alias)
        select v_item_id, trim(x)
        from jsonb_array_elements_text(v_row -> 'qrAliases') as t(x)
        where trim(x) <> ''
        on conflict (item_id, alias) do nothing;
      end if;
    else
      v_added := v_added + 1;
      v_item_id := gen_random_uuid();
      insert into public.inventory_items (
        id, production_id, kind, name, size, notes, condition, stable_public_id
      )
      values (
        v_item_id,
        p_production_id,
        v_kind,
        v_name,
        v_size,
        v_notes,
        v_condition,
        v_item_id::text
      );

      if jsonb_typeof(v_row -> 'qrAliases') = 'array' then
        insert into public.item_qr_aliases (item_id, alias)
        select v_item_id, trim(x)
        from jsonb_array_elements_text(v_row -> 'qrAliases') as t(x)
        where trim(x) <> ''
        on conflict (item_id, alias) do nothing;
      end if;
    end if;
  end loop;

  update public.productions
  set version = version + 1, updated_at = now()
  where id = p_production_id
  returning version into v_cur;

  perform public.fabric_flo_audit(
    p_production_id,
    'inventory_import',
    jsonb_build_object('merged', v_merged, 'added', v_added, 'row_count', v_row_count)
  );

  return jsonb_build_object(
    'merged', v_merged,
    'added', v_added,
    'version', v_cur
  );
end;
$$;

-- ========== 008_fabric_flo_delete_account.sql ==========

-- Self-service account data deletion (App Store / Play compliance).
-- Removes the caller's memberships and sole-admin productions; does not delete auth.users
-- (requires service-role Edge Function or dashboard — see docs/STORE_RELEASE.md).

create or replace function public.fabric_flo_delete_my_account()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_prod_ids uuid[];
  v_deleted_productions int := 0;
  v_removed_memberships int := 0;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  select coalesce(array_agg(distinct pm.production_id), '{}')
  into v_prod_ids
  from public.production_members pm
  where pm.user_id = v_uid
    and pm.role = 'admin'
    and not exists (
      select 1
      from public.production_members pm2
      where pm2.production_id = pm.production_id
        and pm2.user_id <> v_uid
        and pm2.role = 'admin'
    );

  if v_prod_ids is not null and array_length(v_prod_ids, 1) > 0 then
    delete from public.productions p where p.id = any (v_prod_ids);
    get diagnostics v_deleted_productions = row_count;
  end if;

  delete from public.production_members where user_id = v_uid;
  get diagnostics v_removed_memberships = row_count;

  delete from public.production_invites where created_by = v_uid;

  delete from public.user_app_state where user_id = v_uid;

  return jsonb_build_object(
    'deletedProductions', v_deleted_productions,
    'removedMemberships', v_removed_memberships
  );
end;
$$;

grant execute on function public.fabric_flo_delete_my_account() to authenticated;

-- ========== 009_production_settings_scan_method.sql ==========

-- Sync rental house, invite recipients (production settings), and scan method with the app.

alter table public.scan_events
  add column if not exists scan_method text not null default 'qr'
  check (scan_method in ('qr', 'label', 'manual'));

-- ---------------------------------------------------------------------------
-- Pull: include rentalHouseName, inviteRecipients, scanMethod
-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_pull()
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_productions jsonb := '[]'::jsonb;
  v_scans jsonb := '[]'::jsonb;
  v_versions jsonb := '{}'::jsonb;
  r_prod record;
  v_loc jsonb;
  v_items jsonb;
  v_item record;
  v_scan record;
  v_pin text;
  v_qr text[];
  v_method text;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  for r_prod in
    select p.*
    from public.productions p
    join public.production_members m on m.production_id = p.id
    where m.user_id = v_uid
      and p.archived_at is null
    order by p.created_at asc
  loop
    v_versions := v_versions || jsonb_build_object(r_prod.id::text, r_prod.version);

    v_pin := nullif(r_prod.settings ->> 'departmentHeadPin', '');

    select coalesce(jsonb_agg(
      jsonb_build_object(
        'id', l.id,
        'kind', l.kind,
        'name', l.name
      ) order by l.sort_order, l.name
    ), '[]'::jsonb)
    into v_loc
    from public.locations l
    where l.production_id = r_prod.id;

    v_items := '[]'::jsonb;
    for v_item in
      select i.*
      from public.inventory_items i
      where i.production_id = r_prod.id
      order by i.name
    loop
      select coalesce(array_agg(a.alias order by a.created_at), array[]::text[])
      into v_qr
      from public.item_qr_aliases a
      where a.item_id = v_item.id;

      v_items := v_items || jsonb_build_array(
        jsonb_build_object(
          'id', v_item.id,
          'kind', v_item.kind,
          'name', v_item.name,
          'qrAliases', to_jsonb(v_qr),
          'size', v_item.size,
          'notes', v_item.notes,
          'condition', v_item.condition
        )
      );
    end loop;

    v_productions := v_productions || jsonb_build_array(
      jsonb_build_object(
        'id', r_prod.id,
        'name', r_prod.name,
        'createdAt', to_jsonb(r_prod.created_at),
        'departmentHeadPin', to_jsonb(v_pin),
        'rentalHouseName', to_jsonb(nullif(r_prod.settings ->> 'rentalHouseName', '')),
        'inviteRecipients', coalesce(r_prod.settings -> 'inviteRecipients', '[]'::jsonb),
        'locations', coalesce(v_loc, '[]'::jsonb),
        'items', coalesce(v_items, '[]'::jsonb)
      )
    );
  end loop;

  for v_scan in
    select s.*
    from public.scan_events s
    where public.is_production_member(s.production_id)
    order by s.scanned_at desc
  loop
    v_method := coalesce(nullif(trim(v_scan.scan_method), ''), 'qr');
    if v_method not in ('qr', 'label', 'manual') then
      v_method := 'qr';
    end if;

    v_scans := v_scans || jsonb_build_array(
      jsonb_build_object(
        'id', v_scan.id,
        'productionId', v_scan.production_id,
        'itemId', v_scan.item_id,
        'itemKind', v_scan.item_kind,
        'itemName', v_scan.item_name,
        'locationId', coalesce(v_scan.location_id::text, ''),
        'locationKind', v_scan.location_kind,
        'locationLabel', v_scan.location_label,
        'scannedAt', to_jsonb(v_scan.scanned_at),
        'rawQr', v_scan.raw_qr,
        'scanMethod', to_jsonb(v_method),
        'idempotencyKey', to_jsonb(v_scan.idempotency_key)
      )
    );
  end loop;

  return jsonb_build_object(
    'productions', v_productions,
    'scanLog', v_scans,
    'activeProductionId', null::jsonb,
    'versions', v_versions
  );
end;
$$;

-- ---------------------------------------------------------------------------
-- Push: persist rentalHouseName, inviteRecipients, scanMethod (005 body + fields)
-- ---------------------------------------------------------------------------
create or replace function public.fabric_flo_push(p_state jsonb, p_expected_versions jsonb default '{}'::jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_prod record;
  v_pid uuid;
  v_exp bigint;
  v_cur bigint;
  v_loc jsonb;
  v_item jsonb;
  v_scan jsonb;
  v_sid uuid;
  v_settings jsonb;
  v_versions jsonb := '{}'::jsonb;
  v_ik text;
  v_update_count int;
  v_item_count int;
  v_loc_count int;
  v_scan_count int;
  v_method text;
begin
  if v_uid is null then
    raise exception 'not_authenticated';
  end if;

  if p_state is null or jsonb_typeof(p_state -> 'productions') <> 'array' then
    raise exception 'invalid_state';
  end if;

  for v_prod in select * from jsonb_array_elements(coalesce(p_state -> 'productions', '[]'::jsonb))
  loop
    v_pid := (v_prod.value ->> 'id')::uuid;
    if v_pid is null then
      continue;
    end if;

    if not exists (select 1 from public.productions where id = v_pid) then
      raise exception 'unknown_production %', v_pid;
    end if;

    if not public.is_production_member(
      v_pid,
      array['admin', 'department_head', 'crew']::text[]
    ) then
      raise exception 'forbidden_production %', v_pid;
    end if;

    if p_expected_versions ? v_pid::text then
      v_exp := (p_expected_versions ->> v_pid::text)::bigint;
      select version into v_cur from public.productions where id = v_pid for update;
      if v_cur is distinct from v_exp then
        raise exception 'version_conflict'
          using errcode = 'P0001',
            message = format('production=%s server_version=%s', v_pid, v_cur);
      end if;
    end if;

    delete from public.scan_events where production_id = v_pid;
    delete from public.item_qr_aliases a
      using public.inventory_items i
      where a.item_id = i.id and i.production_id = v_pid;
    delete from public.inventory_items where production_id = v_pid;
    delete from public.locations where production_id = v_pid;

    v_settings := coalesce(v_prod.value -> 'settings', '{}'::jsonb);
    if (v_prod.value ? 'departmentHeadPin') then
      v_settings := v_settings || jsonb_build_object(
        'departmentHeadPin',
        nullif(v_prod.value ->> 'departmentHeadPin', '')
      );
    end if;
    if (v_prod.value ? 'rentalHouseName') then
      v_settings := v_settings || jsonb_build_object(
        'rentalHouseName',
        nullif(trim(v_prod.value ->> 'rentalHouseName'), '')
      );
    end if;
    if (v_prod.value ? 'inviteRecipients') then
      v_settings := v_settings || jsonb_build_object(
        'inviteRecipients',
        coalesce(v_prod.value -> 'inviteRecipients', '[]'::jsonb)
      );
    end if;

    update public.productions
    set
      name = coalesce(nullif(trim(v_prod.value ->> 'name'), ''), name),
      settings = coalesce(v_settings, '{}'::jsonb),
      updated_at = now(),
      version = version + 1
    where id = v_pid
    returning version into v_cur;

    get diagnostics v_update_count = row_count;
    if v_update_count = 0 then
      raise exception 'unknown_production %', v_pid;
    end if;

    v_versions := v_versions || jsonb_build_object(v_pid::text, v_cur);

    v_loc_count := 0;
    for v_loc in select * from jsonb_array_elements(coalesce(v_prod.value -> 'locations', '[]'::jsonb))
    loop
      v_loc_count := v_loc_count + 1;
      insert into public.locations (id, production_id, kind, name, sort_order)
      values (
        coalesce((v_loc.value ->> 'id')::uuid, gen_random_uuid()),
        v_pid,
        v_loc.value ->> 'kind',
        v_loc.value ->> 'name',
        coalesce((v_loc.value ->> 'sort_order')::int, 0)
      );
    end loop;

    v_item_count := 0;
    for v_item in select * from jsonb_array_elements(coalesce(v_prod.value -> 'items', '[]'::jsonb))
    loop
      v_item_count := v_item_count + 1;
      v_sid := coalesce((v_item.value ->> 'id')::uuid, gen_random_uuid());
      insert into public.inventory_items (
        id, production_id, kind, name, size, notes, condition, stable_public_id
      )
      values (
        v_sid,
        v_pid,
        v_item.value ->> 'kind',
        v_item.value ->> 'name',
        nullif(trim(v_item.value ->> 'size'), ''),
        nullif(v_item.value ->> 'notes', ''),
        nullif(v_item.value ->> 'condition', ''),
        v_item.value ->> 'id'
      );

      if jsonb_typeof(v_item.value -> 'qrAliases') = 'array' then
        insert into public.item_qr_aliases (item_id, alias)
        select v_sid, trim(x)
        from jsonb_array_elements_text(v_item.value -> 'qrAliases') as t(x)
        where trim(x) <> ''
        on conflict (item_id, alias) do nothing;
      end if;
    end loop;

    select count(*)::int into v_scan_count
    from jsonb_array_elements(coalesce(p_state -> 'scanLog', '[]'::jsonb)) se
    where (se.value ->> 'productionId')::uuid = v_pid;

    perform public.fabric_flo_audit(
      v_pid,
      'bundle_push',
      jsonb_build_object(
        'version', v_cur,
        'locations', v_loc_count,
        'items', v_item_count,
        'scans', v_scan_count
      )
    );
  end loop;

  for v_scan in select * from jsonb_array_elements(coalesce(p_state -> 'scanLog', '[]'::jsonb))
  loop
    v_pid := (v_scan.value ->> 'productionId')::uuid;
    if not exists (
      select 1
      from jsonb_array_elements(coalesce(p_state -> 'productions', '[]'::jsonb)) pe
      where (pe.value ->> 'id')::uuid = v_pid
    ) then
      continue;
    end if;

    if not public.is_production_member(
      v_pid,
      array['admin', 'department_head', 'crew']::text[]
    ) then
      continue;
    end if;

    v_ik := nullif(trim(v_scan.value ->> 'idempotencyKey'), '');
    v_method := coalesce(nullif(trim(v_scan.value ->> 'scanMethod'), ''), 'qr');
    if v_method not in ('qr', 'label', 'manual') then
      v_method := 'qr';
    end if;

    if v_ik is not null then
      insert into public.scan_events (
        id, production_id, item_id, location_id,
        item_kind, item_name, location_kind, location_label,
        scanned_at, raw_qr, scanned_by, idempotency_key, scan_method
      )
      values (
        coalesce((v_scan.value ->> 'id')::uuid, gen_random_uuid()),
        v_pid,
        (v_scan.value ->> 'itemId')::uuid,
        nullif(v_scan.value ->> 'locationId', '')::uuid,
        v_scan.value ->> 'itemKind',
        v_scan.value ->> 'itemName',
        v_scan.value ->> 'locationKind',
        v_scan.value ->> 'locationLabel',
        coalesce((v_scan.value ->> 'scannedAt')::timestamptz, now()),
        v_scan.value ->> 'rawQr',
        v_uid,
        v_ik,
        v_method
      )
      on conflict (idempotency_key) do nothing;
    else
      insert into public.scan_events (
        id, production_id, item_id, location_id,
        item_kind, item_name, location_kind, location_label,
        scanned_at, raw_qr, scanned_by, idempotency_key, scan_method
      )
      values (
        coalesce((v_scan.value ->> 'id')::uuid, gen_random_uuid()),
        v_pid,
        (v_scan.value ->> 'itemId')::uuid,
        nullif(v_scan.value ->> 'locationId', '')::uuid,
        v_scan.value ->> 'itemKind',
        v_scan.value ->> 'itemName',
        v_scan.value ->> 'locationKind',
        v_scan.value ->> 'locationLabel',
        coalesce((v_scan.value ->> 'scannedAt')::timestamptz, now()),
        v_scan.value ->> 'rawQr',
        v_uid,
        null,
        v_method
      );
    end if;
  end loop;

  return jsonb_build_object('ok', true, 'versions', v_versions);
end;
$$;
